config/routes.rb
Rails.application.routes.draw do
  
  root 'top#index'
  resources :dictionaries
  resources :articles
  resources :users
  resources :contacts do
    collection do
      post :confirm
    end
  end
  get '/login', to: 'sessions#new'
  post 'contacts/confirm', to: 'contacts#confirm'
  post '/login', to: 'sessions#create'
  post '/articles' => 'articles#create'
  post '/users/new' => 'users#create'
  post 'contacts/new' => 'contacts#create'
  delete '/logout' , to: 'sessions#destroy'

  root to: 'dictionaries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
	validates :eword, :jword,  presence: true
	validate :add_errors

	belongs_to :user

	def add_errors
		if speech.blank?
			errors[:base] << "choose verb or adv or preposition"
		end

		if grammer.blank?
			errors[:base] << "choose 5 文型"
		end
	end
				
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :name, presence: true
	validates :email, presence: true, uniqueness: true

	has_many :dictionaries
	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 helper_method :current_user
 before_action :login_required

 def current_user
 	@current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
 end

 def login_required
 	redirect_to login_path unless current_user
 end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article,only: [:show, :edit, :update, :destroy]

  def index
  	@articles = Article.all.order(id: 'desc')
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = current_user.articles.new(article_params)
    @user = current_user
    @email = @user.email
  	if @article.save!
  		ArticleMailer.send_article(@article,@email).deliver_now
  		redirect_to articles_path, notice: "articleを追加しました。"
  	end
  end

  def show
  end

  def edit
  end

  def destroy
    article.destroy
    redirect_to articles_path
   end

  private

  def article_params
  	params.require(:article).permit(:word,:user_id)
  end

  def set_article
   @article = current_user.articles.find(params[:id])
 end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  	@contact = Contact.new
  end

  def confirm
  	@contact = Contact.new(contact_params)
  end

  def create
  	@contact = Contact.new(contact_params)
  	if @contact.save
  		ContactMailer.get_contact(@contact).deliver_now
  		flash[:notice] = "Your message was deliverd"
  		redirect_to dictionaries_path
  		# ContactMailer.confirm_contact(@contact).deliver_now
  	end
  end

  private

  def contact_params
  	params.require(:contact).permit(:email, :name, :content)
  end
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  
  before_action :set_dectionary, only: [:edit,:show, :update,:destroy]
  
  def index
    @dictionaries = current_user.dictionaries
  end

  def new
    @dictionary = Dictionary.new
  end

  def create
    @dictionary = current_user.dictionaries.new(dictionary_params)
    if @dictionary.save
      redirect_to dictionaries_url, notice: "#{@dictionary.eword}-#{
      @dictionary.jword} is registerd"
       else
    render :new
   end
  end

  def show
  end

  def edit
  end

  def update
    @dictionary.update!(dictionary_params)
    redirect_to dictionaries_url, notice: "#{@dictionary.eword}を更新しました"
  end

  def destroy
    dictionary.destroy
    redirect_to dictionaries_url, notice: "#{@dictionary.eword}をdeleteしました"
  end

  private

  def dictionary_params
    params.require(:dictionary).permit(:eword, :jword, :speech, :detail, :grammer)
  end
  def set_dectionary
    @dictionary = current_user.dictionaries.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :login_required
  def new
  end

  def create
  	user = User.find_by(email: session_params[:email])

   # Userクラスにhas_secure_passwordして自動で追加された認証のためのメソッド
   # 引数で受け取ったパスワードをハッシュ化してその結果がUserオブジェクト内に保存されてるdigest
   # と一致するか調べる
  	if user&.authenticate(session_params[:password])
  		session[:user_id] = user.id
  		redirect_to dictionaries_path, notice: 'You are logined'
  	else
  		render 'new'
  	end
  end

  def destroy
  	reset_session
  	redirect_to root_path, notice: 'logout'
  end

  private

  def session_params
  	params.require(:session).permit(:email, :password)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required
  
  def index
  	@users = User.all.order(id: "desc")
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		 redirect_to dictionaries_url, notice: "#{@user.name} is registerd"
  		else
  			render :new
  		end
  	end

  def show
  	@user = User.find_by(id: params[:id])
  end

  def update
  	@user = User.find_by(id: params[:id])
  	@user.update
  	redirect_to users_show
  end

  def destroy
  	@user = User.find_by(user_params)
  	@user.dstroy
  	redirect_to login_path
  end


 private

  def user_params
  	 params.require(:user).permit(:name, :email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.slim
h4.title Edit article

nav.justify-content-end
      = link_to 'back lists article', articles_path, class: 'btn btn-primary register'

= form_with model: @article, class: 'container', local: true do |f|
    .form-group
      =f.text_area :word, :cols => "80", :rows => "60"

    .form-group
      =f.submit nil, class: 'btn btn-primary'

app/views/articles/index.html.slim
h4.title Articles
=link_to 'add article', new_article_path, class: 'btn btn-outline register'
=link_to 'back to dictionary', dictionaries_path, class: 'btn btn-outline register'

.container
 - @articles.each do |article|
    ul.article
      =truncate(article.word, :length => 256, :omission => ".....") 
        div.button=link_to 'readmore', edit_article_path(article), class: 'button_readmore btn btn-outline'
        div.button=link_to 'destroy', article, method: :delete, data: { confirm: "This will be delete. Are you sure? " },class: 'button btn btn-outline'

app/views/articles/new.html.slim
h4.title Add article

nav.justify-content-end
      = link_to 'article', articles_path, class: 'btn btn-primary register'

= form_with model: @article, class: 'container', local: true do |f|
    .form-group
      =f.text_area :word, :cols => "80", :rows => "60"

    .form-group
      =f.submit nil, class: 'btn btn-primary'

app/views/articles/show.html.slim
h4.title Articles
=link_to 'add article', new_article_path, class: 'btn btn-primary register'
=link_to 'back to dictionary', dictionaries_path, class: 'btn btn-primary register'
=link_to 'back to article', articles_path, class: 'btn btn-primary register'

.container
    =@article.word

app/views/contacts/confirm.html.slim
h4 request message 


=form_with model: @contact, local: true do |f|
    =f.hidden_field :name
    =f.hidden_field :email
    =f.hidden_field :content 
  
    =f.label :name 
    p=@contact.name
    =f.label :email
    p=@contact.email
    =f.label :content
    p=@contact.content

    =f.submit nil , value: 'send message', class: 'request'

app/views/contacts/new.html.slim
h4 if you want to contact us, feel free to message


=form_with model: @contact, local: true ,url: confirm_contacts_path do |f|
  .form-group
    =f.label :name
    =f.text_field :name, class: 'form-control'
  .form-group
    =f.label :email
    =f.password_field :email, class: 'form-control'
  .form-group
    =f.label :request
    =f.text_area :content, :rows => "5", class: 'form-control'
  .form-group
    =f.submit nil, :value => "request", class: 'request'

app/views/contacts/send.html.slim
h1 Contacts#send
p Find me in app/views/contacts/send.html.slim

app/views/dictionaries/_form.html.slim
- if dictionary.errors.present?
  ul#error_explanation
    -dictionary.errors.full_messages.each do |message|
      .message= message



= form_with model: @dictionary, class: 'container' , local: true do |f|
    .form-group
      = f.label :english
      = f.text_field :eword, class: 'form-control', id: 'task_name'
    .form-group
      = f.label :japanese
      = f.text_field :jword, row:5, class: 'form-control', id: 'dictionary_description'
    .form-group
      = f.label :tips
      = f.text_area :detail, row:5, class: 'form-control'

    .form-check-inline
      =f. radio_button :speech, "adv"
      =f.label :adv ,'adv', class: 'label'

    .form-check-inline
      =f. radio_button :speech, "verb"
      =f.label :verb ,'verb', class: 'label'

    .form-check-inline
      =f. radio_button :speech, "preposition"
      =f.label :preposition ,class: 'label'

    .form-check-inline
      =f.radio_button :grammer, "sv"
      =f.label :grammer , 'sv',class: 'label'

    .form-check-inline
      =f.radio_button :grammer, "svc"
      =f.label :grammer, 'svc' ,class: 'label'

    .form-check-inline
      =f.radio_button :grammer, "svo"
      =f.label :grammer, 'svo' , class: 'label'

    .form-check-inline
      =f.radio_button :grammer, "svoo"
      =f.label :grammer, 'svoo' , class: 'label'

    .form-check-inline
      =f.radio_button :grammer, "svoc"
      =f.label :grammer, 'svoc', class: 'label'
    
    .form-group
    = f.submit nil, class: 'btn btn-outline-primary'

app/views/dictionaries/create.html.slim
h1 Dictionaries#create
p Find me in app/views/dictionaries/create.html.slim

app/views/dictionaries/destroy.html.slim
h1 Dictionaries#destroy
p Find me in app/views/dictionaries/destroy.html.slim

app/views/dictionaries/edit.html.slim
p word edit

.nav-justify-content-end
  = link_to '一覧', dictionary_path, class: 'nav-link'

= render partial: 'form', locals: { dictionary: @dictionary}

app/views/dictionaries/index.html.slim
h4.title English List 

flash[:notice]

= link_to 'add new word', new_dictionary_path, class: 'btn btn-outline register'
= link_to 'go to some articles!', articles_path, class: 'btn btn-outline register'

table.table.table-striped.container
  thead
    tr
      th word
      th meaning
      th speech
      th grammer
      th tips
      th created_at
      th colspan="3"
  tbody
    - @dictionaries.each do |dictionary|
      tr
        td = link_to dictionary.eword, dictionary
        td = dictionary.jword
        td = dictionary.speech
        td = dictionary.grammer
        td = dictionary.detail
        td= dictionary.created_at.strftime("%y.%m.%d")
          =link_to 'edit', edit_dictionary_path(dictionary), class: 'btn btn-outline-primary mr-3'
          =link_to 'destroy', dictionary, method: :delete, data: { confirm: "#{dictionary.eword}will be delete. Are you sure? " },class: 'btn btn-outline-danger'
        

app/views/dictionaries/new.html.slim
h4.title 英単語の新規登録

div.nav-link = link_to 'back to a list', dictionaries_path, class: 'btn btn-outline'

= render partial: 'form', locals: {dictionary: @dictionary}

app/views/dictionaries/show.html.slim
h4.title English detail and tips

div.nav-link = link_to 'back', dictionaries_path, class: 'btn btn-primary'

h4.title = "#{@dictionary.eword} - (#{@dictionary.jword})"

tip

= form_with model: @dictionary ,class: 'container' ,local: true do |f|
    .form-check-inline
      =f. radio_button :speech, "adv"
      =f.label :adv , 'adv', class: 'label'
    .form-check-inline
      =f. radio_button :speech, "verb"
      =f.label :verb , 'verb', class: 'label'

    .form-check-inline
      =f.radio_button :grammer, "svo"
      =f.label :grammer , 'svo', class: 'label'

    .form-check-inline
      =f.radio_button :grammer, "svc"
      =f.label :grammer, 'svc' , class: 'label'

    .form-check-inline
      =f.radio_button :grammer, "svoo"
      =f.label :grammer, 'svoo' , class: 'label'

    .form-check-inline
      =f.radio_button :grammer, "svoc"
      =f.label :grammer, 'svoc' , class: 'label'

    .form-check-inline
      =f.radio_button :grammer, ""
      =f.text_field :grammer, class: 'label'

    =f.text_area :detail, :cols => "60", :rows => "10"


    .form-group
      = f.submit nil, class: 'btn btn-primary'

app/views/dictionaries/update.html.slim
h1 Dictionaries#update
p Find me in app/views/dictionaries/update.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
     | English
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand = link_to 'English', root_path, class: 'nav-link'

      ul.navbar-nav.ml-auto
        -if current_user
          li.nav-item= link_to 'logout', logout_path, method: :delete, class: 'nav-link'
          li.nav-item= link_to 'contact', new_contact_path, class: 'nav-link'
          li.nav-item= link_to 'user', users_path, class: 'nav-link'
        -else
          li.nav-item= link_to 'login', login_path, class: 'nav-link'
          li.nav-item= link_to 'sign up', new_user_path, class: 'nav-link'


    .container
      -if flash.notice.present?
        .alert.alert-success = flash.notice
      = yield

app/views/top/index.html.slim
.top-image

  h1.top-explanation Welcome to your stock english article .
  h2.top-explanation2 you can get a email which additional article

  =link_to 'enter', login_path, class: 'enter-button'

app/views/users/index.html.slim
h4 ユーザー一覧

table.table.table-hover
  thead.thead-default
    tr
      th= User.name
  tbody

    -@users.each do |user|
      tr
        td= link_to user.name , users_path
  

.form-group
  div.user= link_to 'back to dictionary', dictionaries_path, class:  'register'
  div.user= link_to 'going to article' , articles_path, class: 'register'

app/views/users/new.html.slim
-if @user.errors.present?
  ul#error_explanation
    -@user.errors.full_messages.each do |message|
      .message= message

=form_with model: @user, class: 'container, top-image', local: true do |f|
  .form_group.contaier
    =f.label :name 
    =f.text_field :name, class: 'form-control', id: 'session_name'
  .form-group
    =f.label :email
    =f.text_field :email, class: 'form-control', id: 'session_email'
  .form-group
    =f.label :password
    =f.password_field :password, class: 'form-control', id: 'session_password'
  .form-group
    =f.label :password_confirmation, 'password-confirm'
    =f.password_field :password_confirmartion, class: 'form-control', id: 'password_confirm'

  .form-group
    =f.submit nil, class: 'btn btn-primary'